### ISSUE TITLE
Invalid fetchCounts on cassandra types

### ISSUE THREAD

**Issue by c3-JackWennerstrum** [JackDeDobb/c3-data-transfer-tool#11]
When fetch[count]ing cassandra types, filters can only be applyed on indexed fields.  The default filter of `1 == 1` thus results in an invalid fetch[count] call and returns the following error:

```
Unsuccessful fetchCount of type FinancialStatementBaseStateHistory w/ status code: 500
Error Message: <error version="2.0">
  <type>
    <module>metadata</module>
    <name>C3Error</name>
  </type>
  <id>6545.94</id>
  <message>Invalid query [Query -  Root Type: FinancialStatementBaseStateHistory Projections: [Projection: p1 : count()]] Filter: [Filter: 1 == 1]: Filter by parent is required when applying any other filter.</message>
  <codes>
    <k>0</k>
    <v>NotClassified</v>
  </codes>
</error>
```

**Comment by c3-JackWennerstrum** [comment]
One way to get around this is by setting the filter equal to the empty string, but I wonder if the empty string should be the default filter rather than `1 == 1`

**Comment by JackDeDobb** [comment]
Fixed via https://github.com/JackDeDobb/c3-data-transfer-tool/pull/19
