### ISSUE TITLE
FileSystem Root URL contains extra "/"

### ISSUE THREAD

**Issue by c3-JackWennerstrum** [JackDeDobb/c3-data-transfer-tool#12]
When constructing the File System path to send gzip files to, we add an extra "/" to the path in the following line

https://github.com/JackDeDobb/c3-data-transfer-tool/blob/2d51fbb677373ce78c2c42b5b28b9da72a93de55/c3-data-transfer-tool/src/c3DataMigration/c3Helpers/c3FileSystem.py#L49

This is because `getRemoteRootURL` (typically) returns the value `c3fs:///` and any path information should immediately follow.  By using the syntax `'/'.join([rootUrl, ...])` we insert a fourth `/` after `c3fs:///`

**Comment by JackDeDobb** [comment]
Fixed via https://github.com/JackDeDobb/c3-data-transfer-tool/pull/18
